/**
 * TEA Guardrail Tests — Story 6.3: Quick Reports
 * Generated by TEA *automate workflow
 *
 * Tests coverage gaps identified during post-implementation analysis:
 * - [P0] REPORT_PRESETS constants contract (titles, types, stat keys)
 * - [P0] formatStatValue pure-function contract (edge cases)
 * - [P1] Generate button accessibility labels for all 3 card types
 * - [P1] Export params contract per report type (dateRange, filters)
 * - [P1] Independent loading state per card (AC7)
 * - [P1] Button disabled state during generation (AC7)
 * - [P2] Stats display with zero values
 * - [P2] Stats display with null stats and not loading (AC9)
 * - [P2] Export page section layout contract (AC1, AC11)
 *
 * Note: Date range boundary tests are in a separate file
 * (story-6-3-date-utils.guardrail.test.ts) to keep file size lean.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { CalendarDays, CalendarRange, Calendar } from 'lucide-react';
import { ReportCard } from '@/components/export/report-card';
import { QuickReports, type ReportPreset } from '@/components/export/quick-reports';

// ── Mocks ──────────────────────────────────────────────────────────

const mockExportData = vi.fn();
vi.mock('@/hooks/use-export', () => ({
  useExport: () => ({
    exportData: mockExportData,
    isExporting: false,
  }),
}));

vi.mock('@/lib/report-date-utils', () => ({
  getReportDateRange: (type: string) => {
    if (type === 'daily') {
      return { from: new Date(2026, 0, 31, 0, 0, 0), to: new Date(2026, 0, 31, 23, 59, 59) };
    }
    if (type === 'weekly') {
      return { from: new Date(2026, 0, 26), to: new Date(2026, 0, 31) };
    }
    // monthly
    return { from: new Date(2026, 0, 1), to: new Date(2026, 0, 31) };
  },
  formatReportDateLabel: (type: string) => {
    if (type === 'daily') return 'Jan 31, 2026';
    if (type === 'weekly') return 'Jan 26 - Jan 31, 2026';
    return 'January 2026';
  },
}));

vi.mock('@/hooks/use-quick-reports', () => ({
  useQuickReports: () => ({
    daily: { totalLeads: 5, contacted: 3, closed: 1 },
    weekly: { totalLeads: 50, conversionRate: 25.5, topSalesName: 'Alice' },
    monthly: { totalLeads: 200, conversionRate: 18, totalCampaigns: 12 },
    isLoading: { daily: false, weekly: false, monthly: false },
  }),
}));

// ── Test Fixtures ──────────────────────────────────────────────────

const dailyPreset: ReportPreset = {
  type: 'daily',
  title: 'Daily Summary',
  description: "Today's leads and activity",
  icon: CalendarDays,
  period: 'today',
  stats: [
    { label: 'New Leads', key: 'totalLeads' },
    { label: 'Contacted', key: 'contacted' },
    { label: 'Closed', key: 'closed' },
  ],
};

const weeklyPreset: ReportPreset = {
  type: 'weekly',
  title: 'Weekly Summary',
  description: "This week's performance overview",
  icon: CalendarRange,
  period: 'week',
  stats: [
    { label: 'Total Leads', key: 'totalLeads' },
    { label: 'Conversion', key: 'conversionRate' },
    { label: 'Top Performer', key: 'topSalesName' },
  ],
};

const monthlyPreset: ReportPreset = {
  type: 'monthly',
  title: 'Monthly Summary',
  description: 'Full month metrics and trends',
  icon: Calendar,
  period: 'month',
  stats: [
    { label: 'Total Leads', key: 'totalLeads' },
    { label: 'Conversion', key: 'conversionRate' },
    { label: 'Campaigns', key: 'totalCampaigns' },
  ],
};

// ── Tests ──────────────────────────────────────────────────────────

describe('Story 6.3 Quick Reports — Guardrail Tests', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockExportData.mockResolvedValue(undefined);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  // ── P0: REPORT_PRESETS Constants Contract ────────────────────────
  /**
   * GUARDRAIL: These presets define the 3 quick report cards on the Export page.
   * Changing titles, stat keys, or types will break the card display and
   * export logic. Any modification MUST be coordinated with the story spec.
   */
  describe('[P0] REPORT_PRESETS Constants Contract', () => {
    it('QuickReports renders exactly 3 preset cards (AC1)', () => {
      // GIVEN: QuickReports component
      render(<QuickReports />);

      // THEN: Exactly 3 Generate buttons (one per card)
      const generateButtons = screen.getAllByRole('button', { name: /generate/i });
      expect(generateButtons).toHaveLength(3);
    });

    it('Daily preset has correct title and stat keys (AC2)', () => {
      // GIVEN: Daily preset rendered
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 10, contacted: 5, closed: 2 }} isLoading={false} />);

      // THEN: Title matches AC2
      expect(screen.getByText('Daily Summary')).toBeInTheDocument();
      // THEN: Stat labels match spec
      expect(screen.getByText('New Leads')).toBeInTheDocument();
      expect(screen.getByText('Contacted')).toBeInTheDocument();
      expect(screen.getByText('Closed')).toBeInTheDocument();
    });

    it('Weekly preset has correct title and stat keys (AC3)', () => {
      // GIVEN: Weekly preset rendered
      render(<ReportCard preset={weeklyPreset} stats={{ totalLeads: 50, conversionRate: 25, topSalesName: 'Alice' }} isLoading={false} />);

      // THEN: Title matches AC3
      expect(screen.getByText('Weekly Summary')).toBeInTheDocument();
      // THEN: Stat labels match spec
      expect(screen.getByText('Total Leads')).toBeInTheDocument();
      expect(screen.getByText('Conversion')).toBeInTheDocument();
      expect(screen.getByText('Top Performer')).toBeInTheDocument();
    });

    it('Monthly preset has correct title and stat keys (AC4)', () => {
      // GIVEN: Monthly preset rendered
      render(<ReportCard preset={monthlyPreset} stats={{ totalLeads: 200, conversionRate: 18, totalCampaigns: 12 }} isLoading={false} />);

      // THEN: Title matches AC4
      expect(screen.getByText('Monthly Summary')).toBeInTheDocument();
      // THEN: Stat labels match spec
      expect(screen.getByText('Total Leads')).toBeInTheDocument();
      expect(screen.getByText('Conversion')).toBeInTheDocument();
      expect(screen.getByText('Campaigns')).toBeInTheDocument();
    });
  });

  // ── P0: formatStatValue Edge Cases ───────────────────────────────
  /**
   * GUARDRAIL: formatStatValue is the single function that determines
   * how all stat values display in all 3 report cards. Edge case bugs
   * here silently corrupt every card's metrics display.
   */
  describe('[P0] formatStatValue Edge Cases via ReportCard', () => {
    it('displays 0 as "0" (not "--" or empty)', () => {
      // GIVEN: Stats with zero values
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 0, contacted: 0, closed: 0 }} isLoading={false} />);

      // THEN: All zeros show as "0"
      const zeros = screen.getAllByText('0');
      expect(zeros).toHaveLength(3);
    });

    it('displays "--" when stats is null and not loading (AC9)', () => {
      // GIVEN: Null stats, not loading
      render(<ReportCard preset={dailyPreset} stats={null} isLoading={false} />);

      // THEN: All 3 stat positions show "--"
      const dashes = screen.getAllByText('--');
      expect(dashes).toHaveLength(3);
    });

    it('displays conversionRate=0 as "0%" (not "--")', () => {
      // GIVEN: Zero conversion rate
      const preset = {
        ...weeklyPreset,
        stats: [{ label: 'Conversion', key: 'conversionRate' }],
      };
      render(<ReportCard preset={preset} stats={{ conversionRate: 0 }} isLoading={false} />);

      // THEN: Shows "0%" not "--"
      expect(screen.getByText('0%')).toBeInTheDocument();
    });

    it('displays negative number correctly', () => {
      // GIVEN: Negative stat value (edge case - shouldn't normally happen)
      const preset = {
        ...dailyPreset,
        stats: [{ label: 'Change', key: 'change' }],
      };
      render(<ReportCard preset={preset} stats={{ change: -5 }} isLoading={false} />);

      // THEN: Negative value rendered
      expect(screen.getByText('-5')).toBeInTheDocument();
    });
  });

  // ── P1: Accessibility Contracts ──────────────────────────────────
  describe('[P1] Accessibility Contract (AC5, WCAG 2.1)', () => {
    it.each([
      { preset: dailyPreset, expected: 'Generate Daily Summary report' },
      { preset: weeklyPreset, expected: 'Generate Weekly Summary report' },
      { preset: monthlyPreset, expected: 'Generate Monthly Summary report' },
    ])('Generate button has correct aria-label: "$expected"', ({ preset, expected }) => {
      // GIVEN: Report card rendered
      render(<ReportCard preset={preset} stats={{ totalLeads: 1 }} isLoading={false} />);

      // THEN: Button has correct accessible label
      const btn = screen.getByRole('button', { name: /generate/i });
      expect(btn).toHaveAttribute('aria-label', expected);
    });

    it('format selector is accessible as combobox (AC6)', () => {
      // GIVEN: Report card rendered
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 1 }} isLoading={false} />);

      // THEN: Select renders as combobox role
      const combobox = screen.getByRole('combobox');
      expect(combobox).toBeInTheDocument();
    });
  });

  // ── P1: Export Params Contract per Report Type ───────────────────
  /**
   * GUARDRAIL: Each report type MUST pass the correct dateRange to exportData.
   * All other filters MUST be 'all'. Default format MUST be 'xlsx'.
   * Changing these breaks the one-click export contract (AC5).
   */
  describe('[P1] Export Params Contract (AC5)', () => {
    it('Daily card passes today date range and default filters', async () => {
      // GIVEN: Daily card
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 5 }} isLoading={false} />);

      // WHEN: Generate clicked
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Correct params passed
      expect(mockExportData).toHaveBeenCalledWith({
        format: 'xlsx',
        dateRange: {
          from: new Date(2026, 0, 31, 0, 0, 0),
          to: new Date(2026, 0, 31, 23, 59, 59),
        },
        status: 'all',
        owner: 'all',
        campaign: 'all',
      });
    });

    it('Weekly card passes week date range', async () => {
      // GIVEN: Weekly card
      render(<ReportCard preset={weeklyPreset} stats={{ totalLeads: 50 }} isLoading={false} />);

      // WHEN: Generate clicked
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Week range passed
      expect(mockExportData).toHaveBeenCalledWith(
        expect.objectContaining({
          format: 'xlsx',
          dateRange: {
            from: new Date(2026, 0, 26),
            to: new Date(2026, 0, 31),
          },
          status: 'all',
          owner: 'all',
          campaign: 'all',
        })
      );
    });

    it('Monthly card passes month date range', async () => {
      // GIVEN: Monthly card
      render(<ReportCard preset={monthlyPreset} stats={{ totalLeads: 200 }} isLoading={false} />);

      // WHEN: Generate clicked
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Month range passed
      expect(mockExportData).toHaveBeenCalledWith(
        expect.objectContaining({
          format: 'xlsx',
          dateRange: {
            from: new Date(2026, 0, 1),
            to: new Date(2026, 0, 31),
          },
          status: 'all',
          owner: 'all',
          campaign: 'all',
        })
      );
    });
  });

  // ── P1: Loading States (AC7) ─────────────────────────────────────
  describe('[P1] Loading States (AC7)', () => {
    it('Generate button is disabled during generation', async () => {
      // GIVEN: exportData that never resolves
      mockExportData.mockImplementation(() => new Promise(() => {}));
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 5 }} isLoading={false} />);

      // WHEN: Generate is clicked
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Button is disabled and shows "Generating..."
      await waitFor(() => {
        expect(screen.getByText('Generating...')).toBeInTheDocument();
      });
      const btn = screen.getByRole('button', { name: /generate daily summary report/i });
      expect(btn).toBeDisabled();
    });

    it('Generate button re-enables after successful export', async () => {
      // GIVEN: exportData resolves
      mockExportData.mockResolvedValue(undefined);
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 5 }} isLoading={false} />);

      // WHEN: Generate is clicked and completes
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Button re-enables with "Generate" text
      await waitFor(() => {
        const btn = screen.getByRole('button', { name: /generate/i });
        expect(btn).not.toBeDisabled();
        expect(screen.getByText('Generate')).toBeInTheDocument();
      });
    });

    it('Generate button re-enables after failed export (AC8)', async () => {
      // GIVEN: exportData rejects
      mockExportData.mockRejectedValue(new Error('Server Error'));
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 5 }} isLoading={false} />);

      // Suppress expected console.error
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

      // WHEN: Generate is clicked and fails
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Button re-enables
      await waitFor(() => {
        const btn = screen.getByRole('button', { name: /generate/i });
        expect(btn).not.toBeDisabled();
      });

      consoleSpy.mockRestore();
    });
  });

  // ── P1: Error Handling (AC8) ─────────────────────────────────────
  describe('[P1] Error Handling (AC8)', () => {
    it('logs error to console when export fails', async () => {
      // GIVEN: exportData rejects with specific error
      const error = new Error('Network timeout');
      mockExportData.mockRejectedValue(error);
      const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});

      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 5 }} isLoading={false} />);

      // WHEN: Generate is clicked
      await userEvent.click(screen.getByRole('button', { name: /generate/i }));

      // THEN: Error is logged with context message
      await waitFor(() => {
        expect(consoleSpy).toHaveBeenCalledWith('Quick report generation failed:', error);
      });

      consoleSpy.mockRestore();
    });
  });

  // ── P1: Skeleton Loading (AC9) ───────────────────────────────────
  describe('[P1] Skeleton Loading States (AC9)', () => {
    it('shows skeleton loaders when isLoading=true', () => {
      // GIVEN: Card in loading state
      render(<ReportCard preset={dailyPreset} stats={null} isLoading={true} />);

      // THEN: Skeletons are shown for each stat
      const skeletons = document.querySelectorAll('[data-testid="stat-skeleton"]');
      expect(skeletons).toHaveLength(3);
    });

    it('Generate button is still clickable during stats loading (AC9)', () => {
      // GIVEN: Card loading stats
      render(<ReportCard preset={dailyPreset} stats={null} isLoading={true} />);

      // THEN: Generate button is NOT disabled (export doesn't depend on preview)
      const btn = screen.getByRole('button', { name: /generate/i });
      expect(btn).not.toBeDisabled();
    });

    it('card title and description are visible during loading', () => {
      // GIVEN: Card in loading state
      render(<ReportCard preset={dailyPreset} stats={null} isLoading={true} />);

      // THEN: Title and description still visible
      expect(screen.getByText('Daily Summary')).toBeInTheDocument();
      expect(screen.getByText("Today's leads and activity")).toBeInTheDocument();
    });
  });

  // ── P2: Stats Display Edge Cases ─────────────────────────────────
  describe('[P2] Stats Display Edge Cases', () => {
    it('displays large numbers correctly', () => {
      // GIVEN: Large stat values
      render(<ReportCard preset={dailyPreset} stats={{ totalLeads: 99999, contacted: 50000, closed: 25000 }} isLoading={false} />);

      // THEN: Large numbers rendered correctly
      expect(screen.getByText('99999')).toBeInTheDocument();
      expect(screen.getByText('50000')).toBeInTheDocument();
      expect(screen.getByText('25000')).toBeInTheDocument();
    });

    it('displays decimal conversionRate with precision', () => {
      // GIVEN: Decimal conversion rate
      const preset = {
        ...weeklyPreset,
        stats: [{ label: 'Conversion', key: 'conversionRate' }],
      };
      render(<ReportCard preset={preset} stats={{ conversionRate: 33.33 }} isLoading={false} />);

      // THEN: Decimal preserved
      expect(screen.getByText('33.33%')).toBeInTheDocument();
    });

    it('displays empty string topSalesName as-is', () => {
      // GIVEN: Empty string name
      const preset = {
        ...weeklyPreset,
        stats: [{ label: 'Top Performer', key: 'topSalesName' }],
      };
      render(<ReportCard preset={preset} stats={{ topSalesName: '' }} isLoading={false} />);

      // THEN: Empty string renders (not "--")
      // Note: empty string is falsy but it's still a valid string value
      const labels = screen.getAllByText('Top Performer');
      expect(labels).toHaveLength(1);
    });
  });

  // ── P2: QuickReports Container Layout ────────────────────────────
  describe('[P2] QuickReports Container Layout (AC1, AC10)', () => {
    it('renders "Quick Reports" heading', () => {
      // GIVEN: QuickReports rendered
      render(<QuickReports />);

      // THEN: Heading visible
      expect(screen.getByText('Quick Reports')).toBeInTheDocument();
    });

    it('renders responsive grid container', () => {
      // GIVEN: QuickReports rendered
      const { container } = render(<QuickReports />);

      // THEN: Grid with responsive breakpoints
      const grid = container.querySelector('.grid');
      expect(grid).toHaveClass('grid-cols-1');
      expect(grid).toHaveClass('md:grid-cols-2');
      expect(grid).toHaveClass('lg:grid-cols-3');
    });

    it('renders all 3 date range labels', () => {
      // GIVEN: QuickReports rendered
      render(<QuickReports />);

      // THEN: All date labels visible
      expect(screen.getByText('Jan 31, 2026')).toBeInTheDocument();
      expect(screen.getByText('Jan 26 - Jan 31, 2026')).toBeInTheDocument();
      expect(screen.getByText('January 2026')).toBeInTheDocument();
    });

    it('renders 3 format selectors all defaulting to xlsx (AC6)', () => {
      // GIVEN: QuickReports rendered
      render(<QuickReports />);

      // THEN: 3 xlsx defaults
      const xlsxLabels = screen.getAllByText('xlsx');
      expect(xlsxLabels).toHaveLength(3);
    });
  });
});
