/**
 * TEA Guardrail Tests — Story 5.7: isSafeUrl XSS Prevention
 * Generated by TEA *automate workflow
 *
 * [P0] Tests for isSafeUrl() function via CampaignEventsTable rendering
 * Validates that javascript:, data:, vbscript:, and malformed URLs are blocked
 */

import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { CampaignEventsTable } from '../../components/campaigns/campaign-events-table';
import type { CampaignEventItem } from '@/types/campaigns';

function createEvent(overrides: Partial<CampaignEventItem> = {}): CampaignEventItem {
  return {
    eventId: 1,
    email: 'test@example.com',
    event: 'click',
    eventAt: '2026-01-30T10:00:00Z',
    url: null,
    ...overrides,
  };
}

const defaultTableProps = {
  page: 1,
  pageSize: 20,
  total: 1,
  totalPages: 1,
  onPageChange: vi.fn(),
};

describe('[P0] isSafeUrl XSS Prevention (Fix #5)', () => {
  it('should render https URL as clickable link', () => {
    const events = [createEvent({ url: 'https://example.com/promo' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    const link = screen.getByRole('link');
    expect(link).toHaveAttribute('href', 'https://example.com/promo');
    expect(link).toHaveAttribute('target', '_blank');
    expect(link).toHaveAttribute('rel', 'noopener noreferrer');
  });

  it('should render http URL as clickable link', () => {
    const events = [createEvent({ url: 'http://example.com/page' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    const link = screen.getByRole('link');
    expect(link).toHaveAttribute('href', 'http://example.com/page');
  });

  it('should NOT render javascript: URL as link (XSS prevention)', () => {
    const events = [createEvent({ url: 'javascript:alert(1)' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    expect(screen.queryByRole('link')).not.toBeInTheDocument();
  });

  it('should NOT render data: URL as link (XSS prevention)', () => {
    const events = [createEvent({ url: 'data:text/html,<script>alert(1)</script>' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    expect(screen.queryByRole('link')).not.toBeInTheDocument();
  });

  it('should NOT render malformed URL as link', () => {
    const events = [createEvent({ url: 'not-a-valid-url' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    expect(screen.queryByRole('link')).not.toBeInTheDocument();
  });

  it('should render dash for null URL', () => {
    const events = [createEvent({ url: null })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    expect(screen.queryByRole('link')).not.toBeInTheDocument();
    // Dash is rendered in a span
    const cells = screen.getAllByRole('cell');
    const urlCell = cells[cells.length - 1]; // last column is URL
    expect(urlCell.textContent).toBe('-');
  });

  it('should NOT render vbscript: URL as link', () => {
    const events = [createEvent({ url: 'vbscript:MsgBox("XSS")' })];
    render(<CampaignEventsTable events={events} {...defaultTableProps} />);

    expect(screen.queryByRole('link')).not.toBeInTheDocument();
  });
});
