/**
 * Campaign Performance Chart - Guardrail Tests
 * Story 5.6: Campaign Performance Chart
 * Generated by TEA *automate workflow
 *
 * Purpose: Prevent regressions on critical fixes (H-1, H-2, L-1)
 * and expand edge-case coverage for acceptance criteria gaps.
 *
 * Priority: P0 = regression guardrails, P1 = edge-case coverage
 *
 * NOTE: Hook-level regression tests (H-1 queryKey, select slicing, error wrapping,
 * sortBy/sortOrder) are in campaign-chart-guardrails-hook.test.tsx to avoid
 * vi.mock conflicts with component-level tests that mock useCampaignChart.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import {
  CampaignPerformanceChart,
  ChartTooltip,
} from '@/components/campaigns/campaign-performance-chart';
import { CampaignChartSkeleton } from '@/components/campaigns/campaign-chart-skeleton';
import { truncateName } from '@/hooks/use-campaign-chart';
import { CHART_COLORS } from '@/lib/chart-config';
import { RATE_BENCHMARKS } from '@/lib/campaign-benchmarks';
import type { ChartDataItem } from '@/types/campaigns';

// ===========================================
// Mock Recharts (SVG rendering not supported in JSDOM)
// ===========================================

const mockRechartsBarChart = vi.hoisted(() => ({
  ResponsiveContainer: ({
    children,
    height,
  }: {
    children: React.ReactNode;
    height: number;
  }) => (
    <div data-testid="responsive-container" data-height={height}>
      {children}
    </div>
  ),
  BarChart: ({
    children,
    data,
  }: {
    children: React.ReactNode;
    data: unknown[];
  }) => (
    <div data-testid="recharts-bar-chart" data-count={data.length}>
      {children}
    </div>
  ),
  Bar: ({ dataKey, fill, name }: { dataKey: string; fill: string; name: string }) => (
    <div data-testid={`bar-${dataKey}`} data-fill={fill} data-name={name} />
  ),
  XAxis: () => <div data-testid="x-axis" />,
  YAxis: ({ dataKey, tick }: { dataKey?: string; tick?: { fontSize: number } }) => (
    <div data-testid="y-axis" data-datakey={dataKey} data-fontsize={tick?.fontSize} />
  ),
  CartesianGrid: () => <div data-testid="cartesian-grid" />,
  Tooltip: ({ content }: { content: React.ReactNode }) => (
    <div data-testid="tooltip">{content}</div>
  ),
  Legend: () => <div data-testid="legend" />,
  ReferenceLine: ({
    x,
    stroke,
    strokeDasharray,
  }: {
    x: number;
    stroke: string;
    strokeDasharray: string;
  }) => (
    <div
      data-testid={`reference-line-${x}`}
      data-x={x}
      data-stroke={stroke}
      data-dasharray={strokeDasharray}
    />
  ),
}));

vi.mock('recharts', () => mockRechartsBarChart);

// ===========================================
// Mock useCampaignChart hook (for component tests)
// ===========================================

const mockUseCampaignChart = vi.fn();
vi.mock('@/hooks/use-campaign-chart', async () => {
  const actual = await vi.importActual<typeof import('@/hooks/use-campaign-chart')>(
    '@/hooks/use-campaign-chart'
  );
  return {
    ...actual,
    useCampaignChart: (options: unknown) => mockUseCampaignChart(options),
  };
});

// ===========================================
// Helpers
// ===========================================

function createTestQueryClient() {
  return new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0 },
    },
  });
}

function ComponentWrapper({ children }: { children: React.ReactNode }) {
  const queryClient = createTestQueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      {children}
    </QueryClientProvider>
  );
}

const mockChartData: ChartDataItem[] = [
  {
    campaignName: 'Spring Campaign',
    campaignId: 1,
    openRate: 35.0,
    clickRate: 7.0,
    delivered: 8000,
  },
  {
    campaignName: 'Q1 Newsletter',
    campaignId: 2,
    openRate: 25.0,
    clickRate: 3.3,
    delivered: 3000,
  },
];

// ===========================================
// P0: Regression Guardrails (Critical Fix Prevention)
// ===========================================

describe('[P0] Regression Guardrails - Story 5-6 Review Fixes', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('[P0] H-2 Fix: Function initializer (no double-render)', () => {
    it('[P0] should call hook with default desktop limit 10 on initial render', () => {
      mockUseCampaignChart.mockReturnValue({
        data: mockChartData,
        isLoading: false,
        isError: false,
        error: null,
        refetch: vi.fn(),
      });

      render(
        <ComponentWrapper>
          <CampaignPerformanceChart />
        </ComponentWrapper>
      );

      // GUARDRAIL: On desktop (≥1024px JSDOM default), default limit should be 10
      // Function initializer sets value immediately (no useEffect double-render)
      const firstCall = mockUseCampaignChart.mock.calls[0][0];
      expect(firstCall).toMatchObject({ limit: 10 });
    });

    it('[P0] should pass truncateLength on first render (not undefined)', () => {
      mockUseCampaignChart.mockReturnValue({
        data: mockChartData,
        isLoading: false,
        isError: false,
        error: null,
        refetch: vi.fn(),
      });

      render(
        <ComponentWrapper>
          <CampaignPerformanceChart />
        </ComponentWrapper>
      );

      // GUARDRAIL: truncateLength must be set on first call (function initializer)
      const firstCall = mockUseCampaignChart.mock.calls[0][0];
      expect(firstCall.truncateLength).toBeDefined();
      expect(typeof firstCall.truncateLength).toBe('number');
      expect(firstCall.truncateLength).toBeGreaterThanOrEqual(20);
      expect(firstCall.truncateLength).toBeLessThanOrEqual(25);
    });
  });

  describe('[P0] L-1 Fix: aria-busy boolean type', () => {
    it('[P0] should render aria-busy as boolean true attribute', () => {
      render(<CampaignChartSkeleton />);
      const skeleton = screen.getByTestId('campaign-chart-skeleton');

      // GUARDRAIL: aria-busy must render as "true" in DOM
      expect(skeleton).toHaveAttribute('aria-busy', 'true');
    });
  });
});

// ===========================================
// P1: ChartTooltip Edge Cases (AC#3)
// ===========================================

describe('[P1] ChartTooltip Edge Cases', () => {
  it('[P1] should handle unknown dataKey gracefully (fallback to raw key)', () => {
    const payload = [
      {
        dataKey: 'unknownMetric',
        value: 42.5,
        payload: mockChartData[0],
        color: '#FF0000',
      },
    ];

    render(<ChartTooltip active={true} payload={payload} />);

    // GUARDRAIL: Unknown dataKey should fall back to raw key name
    expect(screen.getByText('unknownMetric:')).toBeInTheDocument();
    expect(screen.getByText('42.5%')).toBeInTheDocument();
  });

  it('[P1] should format percentage with exactly one decimal place', () => {
    const payload = [
      {
        dataKey: 'openRate',
        value: 33.333,
        payload: mockChartData[0],
        color: '#3B82F6',
      },
    ];

    render(<ChartTooltip active={true} payload={payload} />);

    // GUARDRAIL: Must use toFixed(1) for consistent formatting
    expect(screen.getByText('33.3%')).toBeInTheDocument();
  });

  it('[P1] should render nothing when payload is undefined', () => {
    const { container } = render(
      <ChartTooltip active={true} payload={undefined} />
    );
    expect(container.firstChild).toBeNull();
  });

  it('[P1] should format large delivered counts with locale separators', () => {
    const bigDelivered: ChartDataItem = {
      ...mockChartData[0],
      delivered: 1234567,
    };
    const payload = [
      {
        dataKey: 'openRate',
        value: 25.0,
        payload: bigDelivered,
        color: '#3B82F6',
      },
    ];

    render(<ChartTooltip active={true} payload={payload} />);

    // GUARDRAIL: toLocaleString() should format with separators
    expect(screen.getByText(/Delivered: 1,234,567/)).toBeInTheDocument();
  });

  it('[P1] should display both Open Rate and Click Rate entries', () => {
    const payload = [
      {
        dataKey: 'openRate',
        value: 35.0,
        payload: mockChartData[0],
        color: CHART_COLORS.info,
      },
      {
        dataKey: 'clickRate',
        value: 7.0,
        payload: mockChartData[0],
        color: CHART_COLORS.secondary,
      },
    ];

    render(<ChartTooltip active={true} payload={payload} />);

    // GUARDRAIL: Both metric labels must render
    expect(screen.getByText('Open Rate:')).toBeInTheDocument();
    expect(screen.getByText('Click Rate:')).toBeInTheDocument();
  });

  it('[P1] should display zero values correctly', () => {
    const zeroData: ChartDataItem = {
      ...mockChartData[0],
      openRate: 0,
      clickRate: 0,
      delivered: 0,
    };
    const payload = [
      {
        dataKey: 'openRate',
        value: 0,
        payload: zeroData,
        color: '#3B82F6',
      },
    ];

    render(<ChartTooltip active={true} payload={payload} />);

    expect(screen.getByText('0.0%')).toBeInTheDocument();
    expect(screen.getByText('Delivered: 0')).toBeInTheDocument();
  });
});

// ===========================================
// P1: Chart Component State Transitions (AC#4, AC#7)
// ===========================================

describe('[P1] CampaignPerformanceChart State Transitions', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('[P1] should render the limit selector with data-testid (AC#4)', () => {
    mockUseCampaignChart.mockReturnValue({
      data: mockChartData,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Selector must be accessible
    expect(screen.getByTestId('chart-limit-selector')).toBeInTheDocument();
    // Must have combobox role for accessibility
    expect(screen.getByRole('combobox')).toBeInTheDocument();
  });

  it('[P1] should display current limit value in selector', () => {
    mockUseCampaignChart.mockReturnValue({
      data: mockChartData,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Default "Top 10" should be displayed
    expect(screen.getByText('Top 10')).toBeInTheDocument();
  });

  it('[P1] should pass refetch to CampaignsError for retry (AC#7)', () => {
    const mockRefetch = vi.fn();
    mockUseCampaignChart.mockReturnValue({
      data: undefined,
      isLoading: false,
      isError: true,
      error: { message: 'Server error' },
      refetch: mockRefetch,
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Retry button must trigger refetch
    const retryBtn = screen.getByTestId('btn-campaigns-retry');
    retryBtn.click();
    expect(mockRefetch).toHaveBeenCalledTimes(1);
  });

  it('[P1] should handle error with no message property', () => {
    mockUseCampaignChart.mockReturnValue({
      data: undefined,
      isLoading: false,
      isError: true,
      error: { message: undefined },
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Component should render error state even without message
    expect(screen.getByTestId('campaigns-error')).toBeInTheDocument();
  });
});

// ===========================================
// P1: Benchmark Reference Lines Integrity (AC#9)
// ===========================================

describe('[P1] Benchmark Reference Lines Integrity', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUseCampaignChart.mockReturnValue({
      data: mockChartData,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });
  });

  it('[P1] should use RATE_BENCHMARKS.openRate.good (15) for Good line', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const goodLine = screen.getByTestId(`reference-line-${RATE_BENCHMARKS.openRate.good}`);
    expect(goodLine).toBeInTheDocument();

    // GUARDRAIL: Value must come from RATE_BENCHMARKS constant
    expect(goodLine).toHaveAttribute('data-x', String(RATE_BENCHMARKS.openRate.good));
  });

  it('[P1] should use RATE_BENCHMARKS.openRate.excellent (25) for Excellent line', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const excellentLine = screen.getByTestId(`reference-line-${RATE_BENCHMARKS.openRate.excellent}`);
    expect(excellentLine).toBeInTheDocument();

    // GUARDRAIL: Value must come from RATE_BENCHMARKS constant
    expect(excellentLine).toHaveAttribute('data-x', String(RATE_BENCHMARKS.openRate.excellent));
  });

  it('[P1] should use CHART_COLORS.warning for Good benchmark line', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const goodLine = screen.getByTestId('reference-line-15');
    // GUARDRAIL: Color must come from CHART_COLORS.warning
    expect(goodLine).toHaveAttribute('data-stroke', CHART_COLORS.warning);
  });

  it('[P1] should use CHART_COLORS.success for Excellent benchmark line', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const excellentLine = screen.getByTestId('reference-line-25');
    // GUARDRAIL: Color must come from CHART_COLORS.success
    expect(excellentLine).toHaveAttribute('data-stroke', CHART_COLORS.success);
  });

  it('[P1] should use dashed stroke for both benchmark lines', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const goodLine = screen.getByTestId('reference-line-15');
    const excellentLine = screen.getByTestId('reference-line-25');

    // GUARDRAIL: Both lines must be dashed
    expect(goodLine).toHaveAttribute('data-dasharray', '3 3');
    expect(excellentLine).toHaveAttribute('data-dasharray', '3 3');
  });
});

// ===========================================
// P1: Chart Color Consistency (AC#1)
// ===========================================

describe('[P1] Chart Color Contract', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUseCampaignChart.mockReturnValue({
      data: mockChartData,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });
  });

  it('[P1] should use CHART_COLORS.info for Open Rate bar', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const openRateBar = screen.getByTestId('bar-openRate');
    // GUARDRAIL: Must reference CHART_COLORS constant, not hardcoded hex
    expect(openRateBar).toHaveAttribute('data-fill', CHART_COLORS.info);
  });

  it('[P1] should use CHART_COLORS.secondary for Click Rate bar', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const clickRateBar = screen.getByTestId('bar-clickRate');
    // GUARDRAIL: Must reference CHART_COLORS constant, not hardcoded hex
    expect(clickRateBar).toHaveAttribute('data-fill', CHART_COLORS.secondary);
  });
});

// ===========================================
// P1: truncateName Edge Cases
// ===========================================

describe('[P1] truncateName Edge Cases', () => {
  it('[P1] should handle single character name', () => {
    expect(truncateName('A', 25)).toBe('A');
  });

  it('[P1] should handle name exactly at boundary (25 chars)', () => {
    const exactly25 = 'ABCDEFGHIJKLMNOPQRSTUVWXY'; // 25 chars
    expect(truncateName(exactly25, 25)).toBe(exactly25);
  });

  it('[P1] should handle name 1 char over boundary', () => {
    const over25 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'; // 26 chars
    expect(truncateName(over25, 25)).toBe('ABCDEFGHIJKLMNOPQRSTUVWXY...');
  });

  it('[P1] should handle unicode characters', () => {
    const thaiName = 'แคมเปญโปรโมชั่นฤดูร้อน ENEOS';
    // Should truncate based on character count
    const result = truncateName(thaiName, 10);
    expect(result).toHaveLength(13); // 10 chars + '...'
    expect(result).toMatch(/\.\.\.$/);
  });

  it('[P1] should handle whitespace-only names', () => {
    expect(truncateName('   ', 2)).toBe('  ...');
  });
});

// ===========================================
// P1: Empty State Guardrails (AC#6)
// ===========================================

describe('[P1] Empty State Guardrails', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('[P1] should display descriptive empty state text (AC#6)', () => {
    mockUseCampaignChart.mockReturnValue({
      data: [],
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    expect(screen.getByText('No campaign data yet')).toBeInTheDocument();
    expect(
      screen.getByText('Performance chart will appear once campaigns have data')
    ).toBeInTheDocument();
  });

  it('[P1] should NOT show selector in empty state', () => {
    mockUseCampaignChart.mockReturnValue({
      data: [],
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Empty state uses ChartEmptyState without selector
    expect(screen.queryByTestId('chart-limit-selector')).not.toBeInTheDocument();
  });

  it('[P1] should have data-testid on empty state container', () => {
    mockUseCampaignChart.mockReturnValue({
      data: [],
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    expect(screen.getByTestId('campaign-chart-empty')).toBeInTheDocument();
  });
});

// ===========================================
// P1: Responsive Config Defaults (AC#8)
// ===========================================

describe('[P1] Responsive Config Guardrails (AC#8)', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockUseCampaignChart.mockReturnValue({
      data: mockChartData,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });
  });

  it('[P1] should pass truncateLength to useCampaignChart', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: truncateLength must be passed to hook
    const hookCall = mockUseCampaignChart.mock.calls[0][0];
    expect(hookCall).toHaveProperty('truncateLength');
    expect(typeof hookCall.truncateLength).toBe('number');
  });

  it('[P1] should render Y-axis with fontSize from responsive config', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    // GUARDRAIL: Y-axis must receive fontSize from useResponsiveChart
    const yAxis = screen.getByTestId('y-axis');
    const fontSize = Number(yAxis.getAttribute('data-fontsize'));
    // Valid range: 10 (mobile) to 12 (desktop)
    expect(fontSize).toBeGreaterThanOrEqual(10);
    expect(fontSize).toBeLessThanOrEqual(12);
  });

  it('[P1] should use aria-label describing chart content', () => {
    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const chartRegion = screen.getByRole('img');
    expect(chartRegion).toHaveAttribute(
      'aria-label',
      'Campaign performance bar chart comparing Open Rate and Click Rate across campaigns'
    );
  });
});

// ===========================================
// P2: Dynamic Chart Height (AC#8)
// ===========================================

describe('[P2] Dynamic Chart Height', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('[P2] should calculate height as max(300, data.length * 50)', () => {
    // 20 campaigns → max(300, 20*50) = 1000
    const twentyCampaigns: ChartDataItem[] = Array.from({ length: 20 }, (_, i) => ({
      campaignName: `Campaign ${i + 1}`,
      campaignId: i + 1,
      openRate: 50 - i * 2,
      clickRate: 10 - i * 0.3,
      delivered: 1000 * (i + 1),
    }));

    mockUseCampaignChart.mockReturnValue({
      data: twentyCampaigns,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const container = screen.getByTestId('responsive-container');
    expect(container).toHaveAttribute('data-height', '1000');
  });

  it('[P2] should enforce minimum height of 300 for small datasets', () => {
    const oneItem: ChartDataItem[] = [mockChartData[0]]; // 1*50 = 50 < 300

    mockUseCampaignChart.mockReturnValue({
      data: oneItem,
      isLoading: false,
      isError: false,
      error: null,
      refetch: vi.fn(),
    });

    render(
      <ComponentWrapper>
        <CampaignPerformanceChart />
      </ComponentWrapper>
    );

    const container = screen.getByTestId('responsive-container');
    expect(container).toHaveAttribute('data-height', '300');
  });
});
